apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 839931788259.dkr.ecr.ap-northeast-2.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: APP_NAME

            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: APP_PORT

            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENV

            - name: WRITABLE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: WRITABLE_URL

            - name: READONLY_URL
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: READONLY_URL