# backend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-backend
  template:
    metadata:
      labels:
        app: football-backend
    spec:
      containers:
        - name: football-backend
          image: football-backend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: football-config
            - secretRef:
                name: football-secret
---
apiVersion: v1
kind: Service
metadata:
  name: football-backend
spec:
  selector:
    app: football-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort