# configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: football-config
data:
  APP_NAME: "Football Match API"
  DB_READER_HOST: "football-postgres" # 추후에 "Aurora_Reader_addr" 로 변경
  DB_WRITER_HOST: "football-postgres" # 추후에 "Aurora_Writer_addr" 로 변경
  DB_PORT: "5432"
  DB_NAME: "football_db"